program test

use fexp

print*, "Regexp, String, Result, expected result"
print*, "Foo, FooBar, ", match("Foo", "FooBar"), "true"
print*, "Poo, FooBar, ", match("Poo", "FooBar"), "false"
print*, "Bar, FooBar, ", match("Bar", "FooBar"), "true"
print*, "Par, FooBar, ", match("Par", "FooBar"), "false"
print*, "Foo, Foo, ", match("Foo", "Foo"), "true"
print*, "Fo, Foo, ", match("Fo", "Foo"), "true"
print*, "Foo, Fo, ", match("Foo", "Fo"), "false"
print*, "ooB, FooBar, ", match("ooB", "FooBar"), "true"
print*, "ooP, FooBar, ", match("ooP", "FooBar"), "false"
print*, "., FooBar, ", match(".", "FooBar"), "true"
print*, "P., FooBar, ", match("P.", "FooBar"), "false"
print*, "^Foo, FooBar, ", match("^Foo", "FooBar"), "true"
print*, "^Bar, FooBar, ", match("^Bar", "FooBar"), "false"
print*, "Foo$, FooBar, ", match("Foo$", "FooBar"), "false"
print*, "Bar$, FooBar, ", match("Bar$", "FooBar"), "true"
print*, ".*o, FooBar, ", match(".*o", "FooBar"), "true"
print*, "o*o, FooBar, ", match("o*o", "FooBar"), "true"
print*, "P*o, FooBar, ", match("P*o", "FooBar"), "true"
print*, "Fo*o, FooBar, ", match("Fo*o", "FooBar"), "true"
print*, "Po*o, FooBar, ", match("Po*o", "FooBar"), "false"
print*, ".+o, FooBar, ", match(".+o", "FooBar"), "true"
print*, "o+o, FooBar, ", match("o+o", "FooBar"), "true"
print*, "P+o, FooBar, ", match("P+o", "FooBar"), "false"
print*, "Fo+o, FooBar, ", match("Fo+o", "FooBar"), "true"
print*, "Po+o, FooBar, ", match("Po+o", "FooBar"), "false"
print*, "F[po]o, FooBar, ", match("F[po]o", "FooBar"), "true"
print*, "F[op]o, FooBar, ", match("F[op]o", "FooBar"), "true"
print*, "F[qp]o, FooBar, ", match("F[qp]o", "FooBar"), "false"
print*, "F[^po]o, FooBar, ", match("F[^po]o", "FooBar"), "false"
print*, "F[^op]o, FooBar, ", match("F[^op]o", "FooBar"), "false"
print*, "F[^qp]o, FooBar, ", match("F[^qp]o", "FooBar"), "true"
print*, "F\do, FooBar, ", match("F\do", "FooBar"), "false"
print*, "F\wo, FooBar, ", match("F\wo", "FooBar"), "true"
print*, "F\do, F5oBar, ", match("F\do", "F5oBar"), "true"
print*, "F\wo, F5oBar, ", match("F\wo", "F5oBar"), "true"
print*, "F\Do, FooBar, ", match("F\Do", "FooBar"), "true"
print*, "F\Wo, FooBar, ", match("F\Wo", "FooBar"), "false"
print*, "F\Do, F5oBar, ", match("F\Do", "F5oBar"), "false"
print*, "F\Wo, F5oBar, ", match("F\Wo", "F5oBar"), "false"
print*, "F[po]*o, FooBar, ", match("F[po]*o", "FooBar"), "true"
print*, "F[op]*o, FooBar, ", match("F[op]*o", "FooBar"), "true"
print*, "F[qp]*o, FooBar, ", match("F[qp]*o", "FooBar"), "true"
print*, "P[qp]*o, FooBar, ", match("P[qp]*o", "FooBar"), "false"


print*, "F[qpo, FooBar, Stops!"
print*, match("F[qpo", "FooBar")

end program test
